In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Titanic.csv')
df.head()

,Name,PClass,Age,Sex,Survived
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0
4,"Allison, Master Hudson Trevor",1st,0.92,male,1

In [5]:
print("Information : ")
df.info()
print("Description : ")
df.describe()

Information :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      1313 non-null   object
 1   PClass    1312 non-null   object
 2   Age       756 non-null    float64
 3   Sex       1313 non-null   object
 4   Survived  1313 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 51.4+ KB
Description :

              Age     Survived
count  756.000000  1313.000000
mean    30.397989     0.342727
std     14.259049     0.474802
min      0.170000     0.000000
25%     21.000000     0.000000
50%     28.000000     0.000000
75%     39.000000     1.000000
max     71.000000     1.000000

In [9]:
df.shape

(1313, 5)

In [13]:
print("Null Values  : ")
df.isnull().sum()

Null Values  :

Name          0
PClass        1
Age         557
Sex           0
Survived      0
dtype: int64

In [15]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

df.isnull().sum()

Name        0
PClass      1
Age         0
Sex         0
Survived    0
dtype: int64

In [25]:
df['PClass'] = df['PClass'].fillna(df['PClass'].mode()[0])

df.isnull().sum()

Name        0
PClass      0
Age         0
Sex         0
Survived    0
dtype: int64

In [27]:
print("Categorical to numeric : ")
df = pd.get_dummies(df, columns=["Sex"], dtype=int)
df.head()

Categorical to numeric :

,Name,PClass,Age,Survived,Sex_female,Sex_male
0,"Allen, Miss Elisabeth Walton",1st,29.00,1,1,0
1,"Allison, Miss Helen Loraine",1st,2.00,0,1,0
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,0,0,1
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,0,1,0
4,"Allison, Master Hudson Trevor",1st,0.92,1,0,1